clinical_cdm_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA_TRANSFORM', env_var('SNOWFLAKE_SCHEMA_RAW')) }}"
      authenticator: oauth
      token: "{{ env_var('SNOWFLAKE_OAUTH_TOKEN') }}"
      client_session_keep_alive: true
      threads: 4

