from src.snowflake_utils import execute_sql, SnowflakeConfig
CFG = SnowflakeConfig()

BOOTSTRAP = f"""
CREATE WAREHOUSE IF NOT EXISTS {CFG.warehouse} WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE DATABASE IF NOT EXISTS {CFG.database};

CREATE SCHEMA IF NOT EXISTS {CFG.schema_raw};
CREATE SCHEMA IF NOT EXISTS {CFG.schema_stg};
CREATE SCHEMA IF NOT EXISTS {CFG.schema_silver};
CREATE SCHEMA IF NOT EXISTS {CFG.schema_gold};

-- Roles (simplified for demo)
CREATE ROLE IF NOT EXISTS ROLE_CDM_ENGINEER;
CREATE ROLE IF NOT EXISTS ROLE_CDM_ANALYST;

GRANT USAGE ON WAREHOUSE {CFG.warehouse} TO ROLE ROLE_CDM_ENGINEER;
GRANT USAGE ON DATABASE {CFG.database} TO ROLE ROLE_CDM_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE {CFG.database} TO ROLE ROLE_CDM_ENGINEER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE {CFG.database} TO ROLE ROLE_CDM_ENGINEER;

GRANT USAGE ON DATABASE {CFG.database} TO ROLE ROLE_CDM_ANALYST;
GRANT USAGE ON SCHEMA {CFG.database}.{CFG.schema_gold} TO ROLE ROLE_CDM_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA {CFG.database}.{CFG.schema_gold} TO ROLE ROLE_CDM_ANALYST;

-- Masking policy for USUBJID (demo)
CREATE OR REPLACE MASKING POLICY MASK_USUBJID AS (val string) RETURNS string ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_CDM_ENGINEER') THEN val
    ELSE regexp_replace(val, '^(.*)$', 'SUBJ-****')
  END;

-- Row Access Policy by STUDYID
CREATE OR REPLACE ROW ACCESS POLICY RLS_STUDYID AS (STUDYID STRING) RETURNS BOOLEAN ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_CDM_ENGINEER') THEN TRUE
    WHEN CURRENT_ROLE() = 'ROLE_CDM_ANALYST' THEN STUDYID IN (CURRENT_ROLE())  -- Replace with mapping table in real life
    ELSE FALSE
  END;
"""

def main():
    print("Bootstrapping Snowflake objects ...")
    execute_sql(BOOTSTRAP)
    print("Done.")

if __name__ == "__main__":
    main()
